### PR TITLE
Add profile select

### PR DESCRIPTION
**Pull request by oliverroick**
This PRs main goal is to add profile selection to the profile form. In the progress of implementing the proposed design, I made some fundamental changes to the profile form architecture.

- Forms are now dynamically generated based to the configuration. In the process I removed `ImageSelect` and turned the `ResoourceSelect` into a generic component to render profile options
- Each form component now manages its own value state and validation. We’re relying on platform functionality to submit the form and prevent the from from submitting when fields are invalid.

### CODE REVIEW

**Comment by batpad** [comment]
Sorry for the delayed review here - had some kerfuffle with my local `minikube` setup that took a bit of wrangling to figure out :-/ 

@oliverroick THIS IS LOOKING SO GOOD! I tested multiple profiles, a few different options, it all seems to work really well!

@yuvipanda I have a feeling this is going to make you quite happy :-) . There might be minor things to discuss around the layout and things, I suggest we do that later / ideally when someone can give the whole thing a bit of design thinking.

@oliverroick could you look at the `prettier` issues? Once those are fixed, I'd be very much in favour of merging this to go ahead with adding some tests, etc.

**Comment by batpad** [comment]
@oliverroick ah sorry, I noticed a minor issue -

Steps to reproduce:

 - Don't select any of the profile radio buttons, try and submit form.
 - Correctly, it shows a validation error: "Select a container profile"
 - Now, select any profile radio

Expected:

 - Validation error should go away, now that a radio is selected

Actual:

 - The validation error saying "Select a container profile" remains even after I have selected a radio.

I think there's two options here:

 - Select the first profile option radio by default, so there is always one of the radios selected, so we don't run into this situation
 - Of course, or fix the validation so that once a radio input is selected the "Select a container profile" validation error goes away

**Comment by batpad** [comment]
@oliverroick any idea why this is still failing? https://results.pre-commit.ci/run/github/633634408/1714976827.7lLMyqY9Tp-3-1zrtfUllQ - do we need some eslint config or something?

**Comment by batpad** [comment]
hmm @oliverroick I see that if I try and run `pre-commit run --all` locally, this also now fails on `main`, so I don't think the failure has anything to do with your commits in this branch - not fully sure what's up.

I'll poke around a bit.

**Comment by yuvipanda** [comment]
wheee this is exciting :) Thanks @oliverroick and @batpad!

**Pull request merged**
